* Tasks
** Project plan: Deadline [2014-10-15 Wed]
** Progress report: Deadline [2014-10-15 Wed]    
** Milestone 0: Deadline [2014-10-23 Thu]
*** Design Robot
**** [2014-09-30 Tue]
     added task 
**** [2014-10-13 Mon]
     Started designing the robot. First level has wheels and battery. Still
     need to add casters and sensors onto that level. Decided to make the
     second level circular, so that if the robot hits a wall it is still
     possible to rotate without getting stuck. By the end of the day we
     constructed the two planned layers.
*** Calibrate wheels
**** [2014-09-30 Tue]
     added task

*** Calibrate and set up RGB-D sensor
**** [2014-09-30 Tue]
     added task
**** [2014-10-14 Tue]
     Started looking at how to extract data from the sensor. RGB data can be
     extracted from the /camera/rgb/image_raw topic, where the data array
     stores each point in sequence, with RGB values in order. The depth seems
     to come in a PointCloud2, which has a less obvious structure. Perhaps we
     are not supposed to use /camera/depth/points, but something else? 
     
     http://answers.ros.org/question/192529/calculate-depth-of-a-point-using-kinect/
     suggests the use of /camera/depth/image_rect. Also, perhaps need to
     consider the use of depth registration to match colour/depth images to
     each other (http://wiki.ros.org/openni_launch/Tutorials/QuickStart)
*** Sending signals to the wheels through Arduino
**** [2014-09-30 Tue]
     added task
*** Blob detection
**** [2014-09-30 Tue]
     added task
*** Image processing -> motor control
**** [2014-09-30 Tue]
     added task
*** Turn to centre object then move towards it. Vector based control
**** [2014-09-30 Tue] 
     added task
** Milestone 1: Deadline [2014-11-12 Wed]
*** Complete mechanical structure
**** [2014-10-02 Thu] 
     added task
**** Hull
**** Sensors
***** IR sensor positions
*** Wall following
****  [2014-10-02 Thu]
      added task
**** 90 degree turn management
***** [2014-10-02 Thu]
      added task
**** IR sensor calibrations
***** [2014-10-02 Thu]
      added task
**** Keeping specific distance from the wall
***** [2014-10-02 Thu]
      added task
**** RGB-D sensor wall/floor following
***** [2014-10-02 Thu] 
      added task
*** Object identification
**** [2014-10-02 Thu] 
     added task
**** Object/feature database
***** [2014-10-02 Thu]
      added task
**** Sliding window detection
***** [2014-10-02 Thu] 
      added task
**** Feature based detection
***** [2014-10-02 Thu]
      added task
**** Feature comparison method
***** [2014-10-02 Thu] 
      added task
** Milestone 2: Deadline [2014-11-26 Wed]
** Milestone 3: Deadline [2014-12-05 Fri]
* Discussion
** [2014-09-30 Tue]
   Talked about what was needed for the first milestone. Just vague ideas at
   this point.
** [2014-10-02 Thu]
   Worked on lab together, task breakdown for milestone 1, discussing the
   project plan and meeting times
** [2014-10-13 Mon]
   Discussed the design of the robot, drew some diagrams and made measurements.
   Talked about how to make github submissions work with multiple people. Going
   to try and use multiple users on the ras system, putting the main
   organisation repository in some directory external to each user, and with
   each person having a fork of the bits in their own user directory. 

   Set up a group robo on the ras15 nuc so that everyone can modify the stuff
   in there. The main repository will be stored in that user.
